input.onPinPressed(TouchPin.P2, function () {
    music.playTone(196, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(196, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(294, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(294, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(330, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(330, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(294, music.beat(BeatFraction.Whole))
    basic.pause(500)
    music.playTone(262, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(262, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(247, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(247, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(220, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(220, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(196, music.beat(BeatFraction.Whole))
    basic.pause(100)
})
basic.forever(function () {
	
})
